project:
  type: website
  output-dir: docs
execute:
  freeze: auto

website:
  favicon: images/logo.png
  title: ""
  sidebar:
    style: "docked"
    search: false
    contents:
      - href: index.qmd
        text: Homepage
      - href: Teaching/Teaching.qmd
        text: Teaching
      - section: "Learning"
        href: Learning/Learning.qmd
        contents:
          - section: "Python"
            contents:
            - section: "Research"
              contents:
              - text: "SBRD in Random Games"
                href: Learning/Python/Useful/Papers/SBRD.ipynb
            - section: "Useful"
              contents:
              - href: Learning/Python/Useful/Arxiv.qmd
                text: "Arxiv"
              - href: Learning/Python/Useful/Greatest_authors.qmd
                text: "Greatest Authors"
            - section: "Codeforces"
              contents:
              - section: "Easy"
                contents:
                - href: Learning/Python/CF/Easy/1758A.qmd
                  text: 1758A
          - section: "Old Notes"
            contents:
            - href: Learning/Old_Work/OldWork.qmd
              text: Old Work
      - href: main_pages/research.qmd
        text: Research
      - href: main_pages/curriculum.qmd
        text: Curriculum Vitae
      - href: main_pages/miscellanea.qmd
        text: Miscellanea
          
  navbar:
    logo: images/logo.png
    left:
      - text: Domenico Mergoni Cecchelli

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

