project:
  type: website
  output-dir: docs
execute:
  freeze: auto

website:
  favicon: images/logo.png
  title: ""
  sidebar:
    style: "docked"
    search: false
    contents:
      - href: index.qmd
        text: Homepage
      - section: "Teaching"
        href: Teaching/Teaching.qmd
        contents:
          - href: Teaching/FM250.qmd
            text: FM250
          - href: Teaching/MA102_MA103.qmd
            text: MA102/MA103
          - href: Teaching/MA210.qmd
            text: MA210
          - href: Teaching/MA423.qmd
            text: MA423
          - href: Teaching/ME200.qmd
            text: ME200
          - href: Teaching/ME306.qmd
            text: ME306
          - href: Teaching/ST310.qmd
            text: ST310
          - href: Teaching/ST455.qmd
            text: ST455
          - href: Teaching/Pre-sessionals.qmd
            text: Pre-sessionals (MiM/GMiM)
      - section: "Learning"
        href: Learning/Learning.qmd
        contents:
          - section: "Python"
            contents:
            - section: "Useful"
              contents:
              - href: Learning/Python/Useful/Arxiv.qmd
                text: "Arxiv"
              - href: Learning/Python/Useful/Greatest_authors.qmd
                text: "Greatest Authors"
            - section: "Codeforces"
              contents:
              - section: "Easy"
                contents:
                - href: Learning/Python/CF/Easy/1758A.qmd
                  text: 1758A
          - section: "Machine Learning and Statistics"
            contents:
          - section: "Reinforcement Learning"
            contents:
      - href: main_pages/research.qmd
        text: Research
      - href: main_pages/curriculum.qmd
        text: Curriculum Vitae
      - href: main_pages/miscellanea.qmd
        text: Miscellanea
          
  navbar:
    logo: images/logo.png
    left:
      - text: Domenico Mergoni Cecchelli

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

