---
title: "FM250 <small><small><small>(Finance)</small></small></small>"
format: html
---

{{< include /support/_margins_Teaching.qmd >}}

<h3>Course content <small><small><small>(Official)</small></small></small></h3>

-   Net Present Value technique,
-   Introduction to portfolio theory,
-   The Capital Asset Pricing Model (CAPM),
-   Stock market efficiency,
-   Forward and futures contracts, option pricing,
-   Investment decisions and the significance of real options,
-   Capital structure and dividend decisions,
-   Capital restructuring: Initial Public Offering.

<h3>Course material <small><small><small>(Partially mine)</small></small></small></h3>

Of the following material, I only created the notes in the last column. The solution, assignment and lecture material were created by the lecturers. The lectures were presented by Professors Ashwini Agrawal and Linyan Zhu. My role was simply to present the solution to exercises in class. I created the notes that you can find in the last column.

| Day   | Material  | Assignment | Solution  | Personal notes                                                  |
|---------------|---------------|---------------|---------------|---------------|
| Day 1 | [Slides](../Documents_files/FM250/Lecture1.pdf) | [Problem set 1](../Documents_files/FM250/Assignment1.pdf) | [Solutions](../Documents_files/FM250/Solution1.pdf) | [Notes 1](../Documents_files/FM250/Notes_class1.compressed.pdf) |
| Day 2 | [Slides](../Documents_files/FM250/Lecture2.pdf) | [Problem set 2](../Documents_files/FM250/Assignment2.pdf) | [Solutions](../Documents_files/FM250/Solution2.pdf) | [Notes 2](../Documents_files/FM250/Notes_class2.compressed.pdf) |
| Day 3 | [Slides](../Documents_files/FM250/Lecture3.pdf) | [Problem set 3](../Documents_files/FM250/Assignment3.pdf) | [Solutions](../Documents_files/FM250/Solution3.pdf) | [Notes 3](../Documents_files/FM250/Notes_class3.compressed.pdf) |
| Day 4 | [Slides](../Documents_files/FM250/Lecture4.pdf) | [Problem set 4](../Documents_files/FM250/Assignment4.pdf) | [Solutions](../Documents_files/FM250/Solution4.pdf) | [Notes 4](../Documents_files/FM250/Notes_class4.compressed.pdf) |
| Day 5 | [Slides](../Documents_files/FM250/Lecture5.pdf) | [Problem set 5](../Documents_files/FM250/Assignment5.pdf) | [Solutions](../Documents_files/FM250/Solution5.pdf) | [Notes 5](../Documents_files/FM250/Notes_class5.compressed.pdf) |
| Day 6 | [Slides](../Documents_files/FM250/Lecture6.pdf) | [Problem set 6](../Documents_files/FM250/Assignment6.pdf) | [Solutions](../Documents_files/FM250/Solution6.pdf) |  Exam |
| Day 7 | [Slides](../Documents_files/FM250/Lecture7.pdf) | [Problem set 7](../Documents_files/FM250/Assignment7.pdf) | [Solutions](../Documents_files/FM250/Solution7.pdf) |  [Notes 7](../Documents_files/FM250/Notes_class7.compressed.pdf)  |
<!-- | Day 8 | [Slides](../Documents_files/FM250/Lecture8.pdf) | [Problem set 8](../Documents_files/FM250/Assignment8.pdf) | [Solutions](../Documents_files/FM250/Solution8.xlsx) |    |
| Day 9 | [Slides](../Documents_files/FM250/Lecture9.pdf) | [Problem set 9](../Documents_files/FM250/Assignment9.pdf) | [Solutions](../Documents_files/FM250/Solution9.pdf) |    |
| Day 10 | [Slides](../Documents_files/FM250/Lecture10.pdf) | [Problem set 10](../Documents_files/FM250/Assignment10.pdf) | [Solutions](../Documents_files/FM250/Solution10.pdf) |    |
| Day 11 | [Slides](../Documents_files/FM250/Lecture11.pdf) | [Problem set 11](../Documents_files/FM250/Assignment11.pdf) | [Solutions](../Documents_files/FM250/Solution11.pdf) |    |-->

