---
title: "ST455 <small><small><small>(Reinforcement Learning)</small></small></small>"
format: html
---

{{< include /support/_margins_Teaching.qmd >}}

<h3>Course content <small><small><small>(Official)</small></small></small></h3>

This course is about reinforcement learning, covering the fundamental concepts of reinforcement learning framework and solution methods. The focus is on the underlying methodology as well as practical implementation and evaluation using software code. The course will cover the following topics:

-   Introduction: course overview.
-   Foundations of reinforcement learning: Markov decision process, Bellman optimality equation, the existence of optimal stationary policy
-   Dynamic programing and Monte Carlo methods: policy evaluation, policy improvement, policy iteration, value iteration based on dynamic programming, and Monte Carlo methods for reinforcement learning, including Monte Carlo estimation and Monte Carlo control.
-   Temporal difference learning: temporal difference learning, temporal difference prediction, Sarsa, Q-learning and n-step temporal difference predictions, TD(lambda).
-   On-policy prediction and control with approximation: types of function approximators (value and action-value function approximator), gradient based methods for value function prediction, convergence guarantees with linear function approximator, and semi-gradient n-step Sarsa.
-   Q-learning type algorithms with function approximation: q-learning with linear function approximator, fitted q-iteration, deep q-network, double deep q-learning, convergence analysis.
-   Policy gradient methods: policy approximation, REINFORCE, actor-critic methods that combine policy function approximation with action-value function approximation.
-   Trust-region policy optimization: monotonic improvement guarantee, trust-region policy optimization.
-   Batch off-policy evaluation: importance sampling-based method, doubly robust method, marginalized importance sampling, double reinforcement learning.
-   Batch policy optimisation: recent advances in offline reinforcement learning algorithms.

<h3>Material and solutions</h3>

The material follows somehow the content of the famous book by Sutton and Barto. I did not write the following material. My role was simply to present the content of the seminars and the solutions in class.

+------------+--------------------------------------------------------+-----------------------------------------------------------------+--------------------------------------------------------------------------+----------------------------------------------------------------------------+
| Week       | Lecture Notes                                          | Assignment                                                      | Solutions                                                                | Seminar Material                                                           |
+============+========================================================+=================================================================+==========================================================================+============================================================================+
| Week 1     | [Notes](../Documents_files/ST455/Week1/lecture1.pdf)   | [Assignment](../Documents_files/ST455/Week1/Seminar1/HW1.ipynb) | [Solutions](../Documents_files/ST455/Week1/Seminar1/HW1-Solution.ipynb)  | -   [Part 1](../Documents_files/ST455/Week1/Seminar1/Seminar1-Part1.ipynb) |
|            |                                                        |                                                                 |                                                                          | -   [Part 2](../Documents_files/ST455/Week1/Seminar1/Seminar1-Part2.ipynb) |
+------------+--------------------------------------------------------+-----------------------------------------------------------------+--------------------------------------------------------------------------+----------------------------------------------------------------------------+
| Week 2     | [Notes](../Documents_files/ST455/Week2/lecture2.pdf)   | [Assignment](../Documents_files/ST455/Week2/Seminar2/HW2.ipynb) | [Solutions](../Documents_files/ST455/Week2/Seminar2/HW2_solution.ipynb)  | -   [Part 1](../Documents_files/ST455/Week2/Seminar2/Seminar2-Part1.ipynb) |
|            |                                                        |                                                                 |                                                                          | -   [Part 2](../Documents_files/ST455/Week2/Seminar2/Seminar2-Part2.ipynb) |
+------------+--------------------------------------------------------+-----------------------------------------------------------------+--------------------------------------------------------------------------+----------------------------------------------------------------------------+
| Week 3     | [Notes](../Documents_files/ST455/Week3/lecture3.pdf)   |                                                                 | [Solutions](../Documents_files/ST455/Week3/Seminar3/HW3_solution.ipynb)  | [Material](../Documents_files/ST455/Week3/Seminar3/Seminar3.ipynb)         |
+------------+--------------------------------------------------------+-----------------------------------------------------------------+--------------------------------------------------------------------------+----------------------------------------------------------------------------+
| Week 4     | [Notes](../Documents_files/ST455/Week4/lecture4.pdf)   |                                                                 | [Solutions](../Documents_files/ST455/Week4/Seminar4/HW4_solution.ipynb)  | [Material](../Documents_files/ST455/Week4/Seminar4/Seminar4.ipynb)         |
+------------+--------------------------------------------------------+-----------------------------------------------------------------+--------------------------------------------------------------------------+----------------------------------------------------------------------------+
| Week 5     | [Notes](../Documents_files/ST455/Week5/lecture5.pdf)   |                                                                 |                                                                          | [Material](../Documents_files/ST455/Week5/Seminar5/Seminar5.ipynb)         |
+------------+--------------------------------------------------------+-----------------------------------------------------------------+--------------------------------------------------------------------------+----------------------------------------------------------------------------+
| Week 6     | Reading week                                           |                                                                 |                                                                          |                                                                            |
+------------+--------------------------------------------------------+-----------------------------------------------------------------+--------------------------------------------------------------------------+----------------------------------------------------------------------------+
| Week 7     | [Notes](../Documents_files/ST455/Week7/lecture7.pdf)   |                                                                 | [Solutions](../Documents_files/ST455/Week7/Seminar7/HW7_solution.ipynb)  | [Material](../Documents_files/ST455/Week7/Seminar7/Seminar7.ipynb)         |
+------------+--------------------------------------------------------+-----------------------------------------------------------------+--------------------------------------------------------------------------+----------------------------------------------------------------------------+
| Week 8     | [Notes](../Documents_files/ST455/Week8/lecture8.pdf)   |                                                                 | [Solutions](../Documents_files/ST455/Week8/Seminar8/HW8_solution.ipynb)  | [Material](../Documents_files/ST455/Week8/Seminar8/Seminar8.ipynb)         |
+------------+--------------------------------------------------------+-----------------------------------------------------------------+--------------------------------------------------------------------------+----------------------------------------------------------------------------+
| Week 9     | [Notes](../Documents_files/ST455/Week9/lecture9.pdf)   |                                                                 | [Solutions](../Documents_files/ST455/Week9/Seminar9/HW9_solution.ipynb)  | -   [Part 1](../Documents_files/ST455/Week9/Seminar9/Seminar9-Part1.ipynb) |
|            |                                                        |                                                                 |                                                                          | -   [Part 2](../Documents_files/ST455/Week9/Seminar9/Seminar9-Part2.ipynb) |
+------------+--------------------------------------------------------+-----------------------------------------------------------------+--------------------------------------------------------------------------+----------------------------------------------------------------------------+
| Week 10    | [Notes](../Documents_files/ST455/Week10/lecture10.pdf) |                                                                 | [Solutions](../Documents_files/ST455/Week10/Seminar/HW10_solution.ipynb) |                                                                            |
+------------+--------------------------------------------------------+-----------------------------------------------------------------+--------------------------------------------------------------------------+----------------------------------------------------------------------------+
| Week 11    | [Notes](../Documents_files/ST455/Week11/lecture11.pdf) |                                                                 |                                                                          | -   [Part 1](../Documents_files/ST455/Week11/Seminar/Sem11-Part1.ipynb)    |
|            |                                                        |                                                                 |                                                                          | -   [Part 2](../Documents_files/ST455/Week11/Seminar/Sem11-Part2.ipynb)    |
+------------+--------------------------------------------------------+-----------------------------------------------------------------+--------------------------------------------------------------------------+----------------------------------------------------------------------------+
